config:
  auto-save:
    delay: 300
  automessage:
    messages:
    - '&3Nie &6cheatuj &3i tak sie zlapiemy!'
    - '&3Zlapiemy &6cheatera &3w gildii &6= &3ban gildii na 7 dni!'
    - '&3Zalozyciel dostanie bana &6= &3disband gildii!'
    delay: 30
    prefix: '&1&l(&9&lMocnoPomocny&1&l)'
  slotmanager:
    slots: 999
    motd: Szalona ruda!
  helpMessages:
  - '&8#######################################'
  - '&6/gildia - &7komenda od zarzadzania gildiami!'
  - '&8#######################################'
  teleport:
    delay: 5
    spawn:
      cooldown: 3600
  silentjoinleave: true
  welcomemessage:
  - witaj
  randomtp:
    min: -2000
    max: 2000
    groups:
      radius: 5
MySQL:
  Host: localhost:3306
  Username: root
  Password: qwerty
  Database: statystyki
