config:
  gracz:
    exp: 1
    diament: 0.5
    szmaragd: 1.2
    zelazo: 1.5
    zloto: 1.1
    proch: 0.65
    redstone: 1.2
    lapis: 1.5
    perly: 0.1
    obsy: 3.0
    slime: 0.6
    piasek: 1.8
    wegiel: 1.5